language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install coverage
  - pip install gnuplot-py
# command to run tests
script: coverage run -m unittest discover -s Test/
