language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-gnuplot gnuplot
install:
  - pip install coverage
  - pip search gnuplot
# command to run tests
script: coverage run -m unittest discover -s Test/
